image: ubuntu/lts
packages:
    - cargo
sources:
    - https://git.sr.ht/~athorp96/cicd-example
tasks:
 - style: |
    cd cicd-example
    cargo fmt -- --check

 - test: |
    cd cicd-example
    cargo test

 - build-release: |
    cd cicd-xample
    if ! git describe --tags --exact-match HEAD; then exit 0; fi
    cargo build --release

 - deploy: |
    cd cicd-example
    if ! git describe --tags --exact-match HEAD; then exit 0; fi
    scp target/releases/my-sorter this-could-be-the-student-machine
