image: ubuntu/lts
environment:
    PATH: /usr/bin:/home/build/.cargo/bin
packages:
    - curl
sources:
    - https://git.sr.ht/~athorp96/cicd-example
tasks:
 - install-rust: |
     curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > install.sh
     chmod +x install.sh
     ./install.sh -y
     rustup component add clippy
     rustup component add rustfmt

 - style: |
    cd cicd-example
    cargo fmt -- --check

 - test: |
    cd cicd-example
    cargo test

 - build-release: |
    cd cicd-xample
    if ! git describe --tags --exact-match HEAD; then exit 0; fi
    cargo build --release

 - deploy: |
    cd cicd-example
    if ! git describe --tags --exact-match HEAD; then exit 0; fi
    scp target/releases/my-sorter this-could-be-the-student-machine
